### PR TITLE
Added event emitters and listeners for firmware upgrade process

### PR DESCRIPTION
**Pull request by spiderkeys**

### CODE REVIEW

**Comment by BrianAdams** [comment]
Looks good. I'll ready and test with the UI so they can be committed together

**Comment by BrianAdams** [comment]
@spiderkeys are you okay with the following for apis? I'll take care of wiring them through the browser.

Per request adding a "Reset MCU" button.  
"mcu.reset" for the reset

I also need apis for the retry firmware upload:
"plugin.updateManager.retry"

**Comment by spiderkeys** [comment]
The APIs are already set up in platforms/beaglebone/boards/2x/setup.js.

They are:
- "mcu.ResetMCU"
- "mcu.FlashESCs"
- "mcu.RebuildMCUFirmware"
- "mcu.UpdateFirmware" (kicks the entire state machine back to step 0 so it checks ESC and MCU firmware)

Feel free to rename them if those don't work for you.

**Comment by spiderkeys** [comment]
Tying to merge of #146.

**Pull request merged**
